# netlify.toml

[build]
  command = "next build"
  publish = ".next" # Netlify's Next.js plugin handles serving from here

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: Add a general redirect for client-side routing fallback.
# The Next.js plugin usually handles this, but it doesn't hurt to be explicit.
[[redirects]]
  from = "/*"
  to = "/index.html" # Or just "/"
  status = 200